server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Si la ruta no existe físicamente, siempre salta al index.html
        try_files $uri $uri/ /index.html;
    }

    # Cache de archivos estáticos para mayor velocidad
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Redirige errores de servidor también al index para que React los maneje
    error_page 404 /index.html;
}